# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - release/*
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -ldflags "-X 'github.com/Appelfeldt/steganography/cmd/sygo.BuildNumber=${{ github.event.release.tag_name }}'" -v ./...

    - name: Test
      run: go test -v ./...

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build
      run: go build -ldflags "-X 'github.com/Appelfeldt/steganography/cmd/sygo.BuildNumber=${{ github.event.release.tag_name }}'" -v ./...

    - name: Test
      run: go test -v ./...
