# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - '*'
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches: [ "main" ]
  # workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Build windows
      run: env GOOS=windows GOARCH=amd64 go build -o bin/sygo.exe -ldflags "-X 'github.com/Appelfeldt/steganography/cmd/sygo.BuildNumber=${{ github.ref  }}'" -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: ""
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/sygo.exe
        asset_name: sygo.exe
        asset_content_type: application/zip
