# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release-draft

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'
    - name: Build windows
      run: env GOOS=windows GOARCH=amd64 go build -o bin/ -ldflags "-X 'github.com/Appelfeldt/steganography/cmd/sygo.BuildVersion=${{ github.ref_name }}'" -v ./...

    - name: Test
      run: go test -v ./...

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.sha }}-sygo-binary
        path: ./bin/steganography.exe
        retention-days: 1

  create-draft:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Download sygo binary
      uses: actions/download-artifact@v4
      with:
        name: ${{ github.sha }}-sygo-binary
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ github.ref_name }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/steganography.exe
        asset_name: sygo.exe
        asset_content_type: application/zip
